const flowers = [
	{
		name: 'Тюльпан белый',
		img: './assets/buket/1tyulpan-white-500x500.png',
		type: 'Цветы',
		but: 'Меньше 5см.',
		color: 'Белый',
		much: '10',
		flength: '15',
		popular: '0',
	},
	{
		name: 'Букет из роз',
		img: './assets/buket/b1.png',
		type: 'Букет',
		but: 'Больше 5см.',
		color: 'Желтый',
		much: '3',
		flength: '30',
		popular: '1',
	},
	{
		name: 'Букет из роз',
		img: './assets/buket/b2.png',
		type: 'Букет',
		but: 'Больше 5см.',
		color: 'Красный',
		much: '5',
		flength: '30',
		popular: '0',
	},
	{
		name: 'Букет из роз',
		img: './assets/buket/b3.png',
		type: 'Букет',
		but: 'Меньше 5см.',
		color: 'Белый',
		much: '5',
		flength: '30',
		popular: '0',
	},
	{
		name: 'Букет из роз',
		img: './assets/buket/b4.png',
		type: 'Букет',
		but: 'Больше 5см.',
		color: 'Белый',
		much: '5',
		flength: '30',
		popular: '1',
	},
	{
		name: 'Хризантема',
		img: './assets/buket/hr.jpg',
		type: 'Цветы',
		but: 'Больше 5см.',
		color: 'Белый',
		much: '8',
		flength: '35',
		popular: '0',
	},
	{
		name: 'Хризантема',
		img: './assets/buket/hrr.jpg',
		type: 'Цветы',
		but: 'Больше 5см.',
		color: 'Красный',
		much: '3',
		flength: '30',
		popular: '1',
	},
	{
		name: 'Хризантема',
		img: './assets/buket/hry.jpg',
		type: 'Цветы',
		but: 'Больше 5см.',
		color: 'Желтый',
		much: '7',
		flength: '35',
		popular: '0',
	},
	{
		name: 'Корзинка из роз',
		img: './assets/buket/kr.jpg',
		type: 'Корзинка',
		but: 'Меньше 5см.',
		color: 'Красный',
		much: '4',
		flength: '15',
		popular: '1',
	},
	{
		name: 'Корзинка из роз',
		img: './assets/buket/kw.jpeg',
		type: 'Корзинка',
		but: 'Больше 5см.',
		color: 'Белый',
		much: '4',
		flength: '20',
		popular: '0',
	},
	{
		name: 'Корзинка из роз',
		img: './assets/buket/kzh.jpg',
		type: 'Корзинка',
		but: 'Больше 5см.',
		color: 'Желтый',
		much: '2',
		flength: '20',
		popular: '1',
	},
	{
		name: 'Корзинка из роз',
		img: './assets/buket/kzh2.jpeg',
		type: 'Корзинка',
		but: 'Больше 5см.',
		color: 'Желтый',
		much: '2',
		flength: '20',
		popular: '0',
	},
	{
		name: 'Лилия',
		img: './assets/buket/lilia.jpg',
		type: 'Цветы',
		but: 'Больше 5см.',
		color: 'Желтый',
		much: '12',
		flength: '35',
		popular: '0',
	},
	{
		name: 'Лилия',
		img: './assets/buket/liliyaw.jpg',
		type: 'Цветы',
		but: 'Больше 5см.',
		color: 'Белый',
		much: "4",
		flength: '35',
		popular: '1',
	},
	{
		name: 'Роза',
		img: './assets/buket/roza.jpg',
		type: 'Цветы',
		but: 'Больше 5см.',
		color: 'Красный',
		much: '10',
		flength: '20',
		popular: '0',
	},
	{
		name: 'Тюльпан',
		img: './assets/buket/tulpan.png',
		type: 'Цветы',
		but: 'Меньше 5см.',
		color: 'Красный',
		much: '10',
		flength: '15',
		popular: '1',
	},
	{
		name: 'Тюльпан',
		img: './assets/buket/tulpany.jpg',
		type: 'Цветы',
		but: 'Меньше 5см.',
		color: 'Желтый',
		much: '10',
		flength: '15',
		popular: '1',
	},
];

export default flowers;
